name = "local-pickup-generator"
type = "local_pickup_delivery_option_generator"

api_version = "unstable"

[build]
command = "cargo wasi build --release"
path = "target/wasm32-wasi/release/local-pickup-generator.wasm"
watch = [ "src/**/*.rs" ]

[ui.paths]
create = "/"
details = "/"
